# Read the Docs configuration file

# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Optionally set the conda env required to build your docs
python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt