#=========================== SCORPiOs EXAMPLE CONFIGURATION FILE ============================#
##For a full description of supported settings, please take a look at SCORPiOs documentation.#


#----------------------------------------- INPUTS -------------------------------------------#

# INPUT1 - The gene trees to correct, as a single file in New Hampshire Extended (.nhx) format.
trees: data/example/forest.nhx

# INPUT2 - The multiple sequence alignments used to build the trees, as a single fasta file.
alis: data/example/ali.fa.gz

# INPUT3 - The genes coordinates for all duplicated species and outgroup(s).
#one file per species, in BED (.bed) format.
genes: data/example/genes/genes.%s.bed

# INPUT4 - The species tree in Newick format with labelled internal nodes (ancestor names).
species_tree: data/example/species_tree.nwk

# Gene-to-species mapping file : a single text file with two columns: gene_name species_name.
#genes_sp_mapping: data/example/genes_sp_mapping.txt


#----------------------------------------- OUTPUTS ------------------------------------------#

# Provide a job name, which will be appended to the output folder name.
jobname: 'example'


#---------------------------------------- PARAMETERS ----------------------------------------#

# Whole-genome duplication(s) and outgroup(s)
WGDs:
        Clupeocephala: 'Lepisosteus.oculatus,Amia.calva'
        Salmonidae: 'Esox.lucius,Gasterosteus.aculeatus,Oryzias.latipes'

# Whether the average number of syntenic orthologs to include genes in the Orthology Table
# should be optimized: yes ('y') or no ('n'). Default threshold value if not optimized: 2.0.
optimize_synteny_support_threshold: 'y'

# Whether orthologs without synteny support should be discarded from the synteny analysis:
# yes ('y') or no ('n')
filter_otable_nosynteny: 'n'

# Size of the sliding window used in the pairwise synteny analysis:
windowSize: 15

# Cut-off on pairwise synteny similarity scores (between 0 and 1):
cutoff: 0

# Whether branch-lengths should be recomputed after corrections: yes ('y') or no ('n').
brlength: 'y'

# Any species with a poorer assembly quality that should be discarded for synteny analysis.
## Comment out if you want to use all species in the synteny analysis.##
lowcov_sp: 'data/example/lowcov'

# Whether to ignore tree-synteny inconsistencies when an orthogroup graph community contains
# only a single gene: yes ('y') or no ('n'). These are poorly-supported WGD duplication nodes.
ignoreSingleGeneCom: 'y'

# Whether each individual corrected tree and its non-corrected counterpart should be saved,
# each in a .nhx file: yes ('y') or no ('n'). This facilitates direct inspection of corrections.
save_tmp_trees: 'y'

# Whether more detailed intermediary outputs should be saved: yes ('y') or no ('n').
# Setting `save_subtrees_lktest` to 'y' saves, in addition to default outputs:
# - constrained tree topologies
# - profileNJ and TreeBeST synteny-aware trees
# - AU-tests outputs
save_subtrees_lktest: 'y'

# Optionally, use spectral clustering instead of Girvan-Newman for graph community detection.
spectral: 'n'

# Iterative-correction related option, automatically updated by the wrapper iterate_scorpios.sh.
## DO NOT MODIFY MANUALLY even if using iterative mode.##
current_iter: 0


#---------------------------------------- RESSOURCES ----------------------------------------#

# Maximum number of threads (will never use more than this number).
# It will be restricted to the number specified via --cores (1 if --cores is not invoked).
ncores: 14

# Memory (--buffer_size) parameter for a bash sort. If decreased, more /tmp space will be used.
buffer_size: 10G

# Use a parallelization scheme specific to large jobs: yes ('y') or no ('n').
parallel_scheme_large_job: 'n'

# Limit number of cores for the branch length computation (after all corrections).
## Uncomment to reduce RAM usage.##
#limit_threads_for_branch_lengths: 37
